name: Swallow build

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare release environment
    runs-on: ubuntu-latest
    steps:
      - run: env
  build-gui:
    name: Build gui
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows/amd64
            output: Swallow.exe
          - os: macos-latest
            platform: darwin/universal
            # wails bug, mac 的 output file 不生效, 先用这个保证能用
            output: Swallow
          - os: ubuntu-latest
            platform: linux/amd64
            output: Swallow-linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.output }}
          build-platform: ${{ matrix.platform }}
          go-version: 1.22.x
          package: false
      - if: runner.os == 'macOS'
        shell: bash
        run: |
          rm -rf ./build/bin/${{ matrix.output }}.app.zip
          zip -q -r -j ./build/bin/${{matrix.output}}.app.zip ./build/bin/${{matrix.output}}.app
          rm -rf ./build/bin/${{ matrix.output }}.app

      - uses: actions/upload-artifact@v2
        with:
          name: target
          path: build/bin/*

  collect-release:
    name: Collect and release
    needs: [build-gui]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - working-directory: target
        run: |
          ls -al target && ls -R target/
          rm -rf Swallow-amd64-installer.exe
          rm -rf Swallow.pkg
          mv Swallow.app.zip Swallow-darwin.app.zip
      - run: ls -al target && ls -R target/ && file target/
      - uses: actions/upload-artifact@v3
        with:
          name: target-release
          path: target/*

      # release assets
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*